version: '3.1'

services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - 5432:5432
    volumes:
      - ./dbdata:/var/lib/postgresql/data

  adminer:
    image: adminer
    ports:
      - 8800:8080